### ISSUE TITLE
This query seems to be quite heavy for our brand.

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1243]
Site freezes. Tried twice.

![Screenshot 2019-05-04 at 5 19 00 PM](https://user-images.githubusercontent.com/39734400/57178609-d2a6bf00-6e90-11e9-85a8-dfa677c23d78.png)

**Comment by nishant1414** [comment]
Site Freeze due to large amount of data.
you have create 11623 skus in system and this report try to get stock and sale of each sku.
if you can provide me data (inactive skus list on which you are not working now). i can mark them as 
inactive in system. We are  also writing functionality to mark skus as inactive and it will be delivered by monday or tuesday.
